### ISSUE TITLE
[1.15.1] Custom resources broken

### ISSUE THREAD

**Issue by vasyl-purchel** [OrderedChaos-Dev/ProjectVibrantJourneys#90]
Minecraft version: 1.15.1
Forge version: 30.0.20
Project Vibrant Journeys version: 2.0.0
BiomesOPlenty version: 1.15.1-10.0.0.291

Issue: custom resources appear broken in the game, prevent player from moving, in resource packs shows as resource pack built for older version of minecraft and incompatible

In debug logs found this:
```
Couldn't parse data file projectvibrantjourneys:blocks/granite_rocks from projectvibrantjourneys:loot_tables/blocks/granite_rocks.json
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 23 column 1 path $.pools
	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:496) ~[?:?]
	at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:534) ~[?:?]
	at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:48) [?:?]
	at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:22) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$2974/2129874611.get(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.io.EOFException: End of input at line 23 column 1 path $.pools
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:482) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:494) ~[?:?]
```

**Comment by OrderedChaos-Dev** [comment]
I've uploaded an update that fixed the issue with the file.
